import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { AppSidebar } from "@/components/ui/sidebar/app-sidebar";
import UserContextProvider from "./lib/userContext/userContext";
import { getUserAndClassroomData } from "./lib/userContext/contextFetcher";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ClassroomLM",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userData = await getUserAndClassroomData();
  // TODO: change this?

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `font-sans antialiased`,
          geistSans.variable,
          geistMono.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          // disableTransitionOnChange
        >
          {userData ? (
            <SidebarProvider>
              <UserContextProvider userAndClassDataInitial={userData}>
                <AppSidebar />
                <SidebarInset>
                  <main>
                    <SidebarTrigger />
                    {children}
                  </main>
                  <Toaster />
                </SidebarInset>
              </UserContextProvider>
            </SidebarProvider>
          ) : (
            <main>{children}</main>
          )}
        </ThemeProvider>
      </body>
    </html>
  );
}
