import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { AppSidebar } from "@/components/ui/sidebar/app-sidebar";
import { cn } from "./lib/utils";
import UserContextProvider from "./lib/userContext/userContext";
import { getUserAndClassroomData } from "./lib/userContext/contextFetcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ClassroomLM",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userData = await getUserAndClassroomData();
  // TODO: change this?
  if (!userData) {
    return <h1>Server error, please reload</h1>;
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `font-sans antialiased`,
          geistSans.variable,
          geistMono.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          // disableTransitionOnChange
        >
          <SidebarProvider>
            <UserContextProvider userAndClassDataInitial={userData}>
              <AppSidebar />
              <SidebarInset>
                <main>
                  <SidebarTrigger />
                  {children}
                </main>
                <Toaster />
              </SidebarInset>
            </UserContextProvider>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
