services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: dev-team
    container_name: dev-team-sp25
    volumes:
      - ..:/app
    command: sleep infinity
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DATABASE_URI: postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/postgres
    networks:
      - dev
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    # Uncomment ports to access database from your computer (optional)
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_PASSWORD: pgs3cr3t
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres:

networks:
  dev:
